Description: >

    Foodbolt CloudFormation Master template:
      1. Creates resources from VPC template vpc.yaml.
      2. Creates resources from CICD template ecs-template.yaml
      3. Creates resources from ECS template ecs-template.yaml.

Resources:
  VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/spartans-cloudformation-files-2019/template/vpc.yaml
            Parameters:
                EnvironmentName:    !Ref AWS::StackName
                VpcCIDR:            10.180.0.0/16
                PublicSubnet1CIDR:  10.180.8.0/21
                PublicSubnet2CIDR:  10.180.16.0/21
                PrivateSubnet1CIDR: 10.180.24.0/21
                PrivateSubnet2CIDR: 10.180.32.0/21

  ECS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:  https://s3.amazonaws.com/spartans-cloudformation-files-2019/template/ecs-template.yaml
            Parameters:
                InstanceType: t2.micro
                VpcId: !GetAtt VPC.Outputs.VPC
                SubnetID: !GetAtt VPC.Outputs.PublicSubnets

  Build:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/spartans-cloudformation-files-2019/template/cicd.yaml


Outputs:

    MLServiceUrl:
        Description: The URL endpoint for the ML service
        Value: !Join [ "/", [ 'http:/', !GetAtt ECS.Outputs.ECSALB, "image" ]]
